import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

// Auto-generated by: https://github.com/pmndrs/gltfjsx
export default function Model({ url, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(url)
  // useFrame((state) => {
  //   group.current.children.forEach((child, index) => {
  //     child.position.y += Math.sin(index * 1000 + state.clock.elapsedTime) / 50
  //     child.rotation.x += (Math.sin(index * 1000 + state.clock.elapsedTime) * Math.PI) / 2000
  //     child.rotation.y += (Math.cos(index * 1000 + state.clock.elapsedTime) * Math.PI) / 3000
  //     child.rotation.z += (Math.sin(index * 1000 + state.clock.elapsedTime) * Math.PI) / 4000
  //   })
  // })
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.Material}
        geometry={nodes.Object_2.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.Material_Untitled}
        geometry={nodes.Object_3.geometry}
        material-envMapIntensity={0.8}
      />
    </group>
  )
}
