import React, { useRef } from "react";
// import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export default function GPU({ url, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(url);

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.heatsink}
        geometry={nodes.heatsink_heatsink_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.heatsink}
        geometry={nodes.diagonalheatsink_heatsink_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.heatsink}
        geometry={nodes.heatsink1_heatsink_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.fan1}
        geometry={nodes.Cylinder_fan1_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.fan1}
        geometry={nodes.fan_fan1_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.fan1}
        geometry={nodes.fanframe_fan1_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.fan1}
        geometry={nodes.fan_fan1_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.fan1}
        geometry={nodes.fanframe_fan1_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.fan1}
        geometry={nodes.fanblade_fan1_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.bottomfan1__0}
        geometry={nodes.bottomfan1__0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.fan1}
        geometry={nodes.Cylinder001_fan1_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.fan1}
        geometry={nodes.fan001_fan1_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.fan1}
        geometry={nodes.fanframe001_fan1_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.fan1}
        geometry={nodes.bottomfan1001_fan2_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.pciyellow}
        geometry={nodes.pcie_pcieyellow_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.pcieblack}
        geometry={nodes.pcie_pcieblack_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.rtx_3070}
        geometry={nodes.Text_rtx_3070_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.fan2}
        geometry={nodes.bottomfan1002_fan2_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.heatsink}
        geometry={nodes.back_heatsink_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.bracket}
        geometry={nodes.bracket_bracket_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.bracket}
        geometry={nodes.bracket_backplate_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.ports}
        geometry={nodes.ports_ports_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.bracket}
        geometry={nodes.Cylinder003_bracket_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.bracket}
        geometry={nodes.Cylinder004_bracket_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.bracket}
        geometry={nodes.Cylinder005_bracket_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.bracket}
        geometry={nodes.bracketscrew_bracket_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.body}
        geometry={nodes.RTX3070_body_0.geometry}
        material-envMapIntensity={0.8}
      />
      <mesh
        material={materials.backplate}
        geometry={nodes.RTX3070_backplate_0.geometry}
        material-envMapIntensity={0.8}
      />
    </group>
  );
}
